name: Run Python Unittests
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
      - uses: actions/setup-python@v2
        with:
        python-version: '3.x'
      - name: Install pip3
        run: |
          python3 -m pip install --upgrade pip
      - name: Install pytest
        run: |
          pip install pytest
     - name: Test with pytest
        run: |
          pytest